const authors =[
    {author_no:1,author_name:"Jeff Bezos",university:"Princeton University",date_of_birth:"01-01-1987",h_index:01,gender:'m'},
    {author_no:2,author_name:"Francoise Bettencourt Meyers",university:"Harvard University",date_of_birth:"01-01-1954",h_index:02,gender:'f'},
    {author_no:3,author_name:"Elon Musk",university:"Columbia University",date_of_birth:"01-01-1990",h_index:03,gender:'m'},
    {author_no:4,author_name:"Alice Walton",university:"Massachusetts Institute of Technology",date_of_birth:"01-01-1988",h_index:04,gender:'f'},
    {author_no:5,author_name:"Bernard Arnault",university:"Yale University",date_of_birth:"01-01-1965",h_index:05,gender:'m'},
    {author_no:6,author_name:"Mackenzie Scott",university:"Amsterdam",date_of_birth:"01-01-1956",h_index:06,gender:'f'},
    {author_no:7,author_name:"Mackenzie Scott",university:"Stanford University",date_of_birth:"01-01-1980",h_index:07,gender:'m'},
    {author_no:8,author_name:"Julia Koch",university:"Amsterdam",date_of_birth:"01-01-1973",h_index:08,gender:'f'},
    {author_no:9,author_name:"Mark Zuckerberg",university:"Massachusetts Institute of Technology",date_of_birth:"01-01-1990",h_index:09,gender:'m'},
    {author_no:10,author_name:"Yang Huiyan",university:"University of Chicago",date_of_birth:"01-01-1981",h_index:010,gender:'f'},
    {author_no:11,author_name:"Zhong Shanshan",university:"Yale University",date_of_birth:"01-01-1972",h_index:011,gender:'m'},
    {author_no:12,author_name:"Jacqueline Mars",university:"Massachusetts Institute of Technology",date_of_birth:"01-01-1962",h_index:012,gender:'f'},
    {author_no:13,author_name:"Warren Buffet",university:"Harvard University",date_of_birth:"01-01-1951",h_index:013,gender:'m'},
    {author_no:14,author_name:"Susanne Klatten",university:"University of Chicago",date_of_birth:"01-01-1943",h_index:014,gender:'f'},
    {author_no:15,author_name:"Larry Page",university:"Stanford University",date_of_birth:"01-01-1989",h_index:015,gender:'m'},
];
const research_papers = [
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
]